name: CI

on:
  push:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install system deps
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Install ruff
        run: pip install ruff

      - name: Install project
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]

      - name: Lint
        run: ruff check .

      - name: Test
        env:
          DIARIZATION_TEST_MODE: "1"
        run: pytest

      - name: Build Docker
        run: docker build -t automatic-diarization:ci .
